version: '3.8'
services:
    nest:
        build:
            context: .
            dockerfile: ./docker/nest/Dockerfile
        container_name: nest
        expose:
            - 3001
        # ports:
        #     - 3001:3001
        env_file:
            - .env.prod
        restart: always
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: nginx
        # nginx 설정 파일 연동
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        restart: always
        depends_on:
            - nest

    db:
        image: postgres:14.7-alpine
        container_name: postgres
        restart: always
        hostname: 'docker-postgres'
        expose:
            - 5432
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_USER: <DB유저>
            POSTGRES_PASSWORD: <DB패스워드>
            POSTGRES_DB: <DB명>
            PG_DATA: <Postgres 데이터 연동 위치>
